version: "3"

services:
  postgres-db:
    restart: always
    image: postgres:latest
    environment:
      TZ: "Asia/Tehran"
      POSTGRES_DB: bookLand_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U admin -d bookLand_db"]
      interval: 5s
      timeout: 2s
      retries: 10
    networks:
      - my_network
    volumes:
       - ./db-data/postgres/:/var/lib/postgresql/data/
#      - ./SqlScripts.sql:/docker-entrypoint-initdb.d/SqlScripts.sql


  commentservice:
    restart: on-failure
    build:
      context: .
      dockerfile: ./Dockerfile  # This should be the Dockerfile for your Node.js service
    environment:
      - DB_HOST=postgres-db
      - DB_USER=admin
      - DB_PASSWORD=password
      - DB_NAME=bookLand_db
    networks:
      - my_network
    ports:
      - "6002:6002"
    volumes:
      - ./:/app
    depends_on:
      postgres-db:
        condition: service_healthy

networks:
  my_network:
    external: true