version: "3"

services:
  commentservice:
    restart: on-failure
    build:
      context: .
      dockerfile: ./Dockerfile  # This should be the Dockerfile for your Node.js service
    environment:
      - DB_HOST=postgres-db
      - DB_USER=admin
      - DB_PASSWORD=password
      - DB_NAME=bookLand_db
    networks:
      - my_network
    ports:
      - "6002:6002"
    

networks:
  my_network:
    external: true